In [2]:
import pickle

In [3]:
#dates_file = open('dates.pickle', 'wb')
#pickle.dump(dates_dataset, dates_file)
#dates_file.close()

dates_file = open('dataset/dates.pickle', 'rb')
dates = pickle.load(dates_file)
dates_file.close()

In [4]:
dates

[('9 may 1998', '1998-05-09'),
 ('10.09.70', '1970-09-10'),
 ('4/28/90', '1990-04-28'),
 ('thursday january 26 1995', '1995-01-26'),
 ('monday march 7 1983', '1983-03-07'),
 ('sunday may 22 1988', '1988-05-22'),
 ('tuesday july 8 2008', '2008-07-08'),
 ('08 sep 1999', '1999-09-08'),
 ('1 jan 1981', '1981-01-01'),
 ('monday may 22 1995', '1995-05-22'),
 ('friday june 16 1978', '1978-06-16'),
 ('friday june 18 1999', '1999-06-18'),
 ('8 oct 1987', '1987-10-08'),
 ('tuesday april 1 2008', '2008-04-01'),
 ('6 september 2012', '2012-09-06'),
 ('12 november 1981', '1981-11-12'),
 ('friday august 19 2011', '2011-08-19'),
 ('25 08 07', '2007-08-25'),
 ('18 september 1982', '1982-09-18'),
 ('friday february 25 1994', '1994-02-25'),
 ('friday march 19 1976', '1976-03-19'),
 ('20.02.06', '2006-02-20'),
 ('17.01.98', '1998-01-17'),
 ('october 24 2009', '2009-10-24'),
 ('17 apr 2004', '2004-04-17'),
 ('03.05.81', '1981-05-03'),
 ('31 jan 1980', '1980-01-31'),
 ('01 jan 1984', '1984-01-01'),
 ('19 a

In [3]:
#human_vocab_file = open('human_vocab.pickle', 'wb')
#pickle.dump(human_vocab, human_vocab_file)
#human_vocab_file.close()

human_vocab_file = open('dataset/human_vocab.pickle', 'rb')
human_vocab = pickle.load(human_vocab_file)
human_vocab_file.close()

In [4]:
#machine_vocab_file = open('machine_vocab.pickle', 'wb')
#pickle.dump(machine_vocab, machine_vocab_file)
#machine_vocab_file.close()

machine_vocab_file = open('dataset/machine_vocab.pickle', 'rb')
machine_vocab = pickle.load(machine_vocab_file)
machine_vocab_file.close()

In [5]:
#inv_machine_vocab_file = open('inv_machine_vocab.pickle', 'wb')
#pickle.dump(inv_machine_vocab, inv_machine_vocab_file)
#inv_machine_vocab_file.close()

inv_machine_vocab_file = open('dataset/inv_machine_vocab.pickle', 'rb')
inv_machine_vocab = pickle.load(inv_machine_vocab_file)  # variables come out in the order you put them in
inv_machine_vocab_file.close()

In [6]:
from keras.preprocessing.sequence import pad_sequences

Using TensorFlow backend.


In [7]:
X = []
Y = []
for i, date in enumerate(dates):
    index_x = []
    index_y = []
    for j, character in enumerate(date[0]):
        index_x.append(human_vocab.get(character))
    X.append(index_x)
    for j, character in enumerate(date[1]):
        index_y.append(machine_vocab.get(character))
    Y.append(index_y)
    
X = pad_sequences(X, maxlen=30, padding="post", value=36.)

In [8]:
input_encoding = human_vocab
output_encoding = machine_vocab
input_decoding = {v: k for k, v in input_encoding.items()}
output_decoding = {v: k for k, v in output_encoding.items()}

In [9]:
import numpy as np

In [11]:
Xoh = np.zeros(shape=(len(X), 30, 37))
for i, data in enumerate(X): 
    for j, character in enumerate(data): 
        Xoh[i, j, character] = 1.

In [12]:
Yoh = np.zeros(shape=(len(Y), 10, 11))
for i, data in enumerate(Y): 
    for j, character in enumerate(data): 
        Yoh[i, j, character] = 1.

In [13]:
index = 0
print("Source date:", dates[index][0])
print("Target date:", dates[index][1])
print()
print("Source after preprocessing (indices):", X[index])
print("Target after preprocessing (indices):", Y[index])
print()
print("Source after preprocessing (one-hot):", Xoh[index])
print("Target after preprocessing (one-hot):", Yoh[index])

Source date: 9 may 1998
Target date: 1998-05-09

Source after preprocessing (indices): [12  0 24 13 34  0  4 12 12 11 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36
 36 36 36 36 36]
Target after preprocessing (indices): [2, 10, 10, 9, 0, 1, 6, 0, 1, 10]

Source after preprocessing (one-hot): [[ 0.  0.  0. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  1.]
 [ 0.  0.  0. ...,  0.  0.  1.]
 [ 0.  0.  0. ...,  0.  0.  1.]]
Target after preprocessing (one-hot): [[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [14]:
X[index]

array([12,  0, 24, 13, 34,  0,  4, 12, 12, 11, 36, 36, 36, 36, 36, 36, 36,
       36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36])

In [57]:
Xoh_file = open('Xoh.pickle', 'wb')
pickle.dump(Xoh, Xoh_file)
Xoh_file.close()

Yoh_file = open('Yoh.pickle', 'wb')
pickle.dump(Yoh, Yoh_file)
Yoh_file.close()

In [15]:
X_file = open('X.pickle', 'wb')
pickle.dump(X, X_file)
X_file.close()

Y_file = open('Y.pickle', 'wb')
pickle.dump(Y, Y_file)
Y_file.close()